![reference image](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

In [ ]:
import torch
import pandas as pd
import numpy as np

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Get tensor back as Python integer
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
# ndim is number of dimensions
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
matrix = torch.tensor([[5,6],[3,4]])
matrix

tensor([[5, 6],
        [3, 4]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [21]:
# Tensor
tensor = torch.tensor([[[1,2,3],[3,5,6],[3,4,8]],[[3,9,7],[4,7,5],[1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [3, 5, 6],
         [3, 4, 8]],

        [[3, 9, 7],
         [4, 7, 5],
         [1, 2, 3]]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

torch.Size([2, 3, 3])

In [24]:
tensor[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [3, 4, 8]])

In [25]:
## Random tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3951, 0.1169, 0.0232, 0.2959],
        [0.2254, 0.6417, 0.5325, 0.4821],
        [0.0996, 0.9306, 0.8601, 0.6633]])

In [27]:
# Random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.ndim

3

In [28]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [29]:
# Zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
# Range of tensors
range_tensor = torch.arange(start = 0, end=500, step=45)
range_tensor

tensor([  0,  45,  90, 135, 180, 225, 270, 315, 360, 405, 450, 495])

In [44]:
# Tensors like
# Creates a tensor with the same shape as the input tensor
zeros = torch.zeros_like(input=range_tensor)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
# Tensor datatypes
tensorFloat32 = torch.tensor([3.0,5.0,4.0],dtype=torch.float32,device=None,requires_grad=False)
print(f"This is tensor : {tensorFloat32}, this is datatype : {tensorFloat32.dtype}")

This is tensor : tensor([3., 5., 4.]), this is datatype : torch.float32


In [54]:
tensorFloat16 = tensorFloat32.type(torch.float16)
tensorFloat16

tensor([3., 5., 4.], dtype=torch.float16)

In [55]:
tensorFloat16*tensorFloat32

tensor([ 9., 25., 16.])

In [56]:
tensorInt32 = torch.tensor([3,4,5],dtype=torch.int32)
tensorInt32

tensor([3, 4, 5], dtype=torch.int32)

In [58]:
tensorInt32*tensorFloat16

tensor([ 9., 20., 20.], dtype=torch.float16)

In [59]:
# Solving issues

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8349, 0.3782, 0.5964, 0.7879],
        [0.6721, 0.2668, 0.9786, 0.4463],
        [0.7156, 0.2948, 0.5911, 0.6309]])

In [61]:
print(some_tensor)
print(f"datatype : {some_tensor.dtype}")
print(f"shape : {some_tensor.shape}")
print(f"device : {some_tensor.device}")

tensor([[0.8349, 0.3782, 0.5964, 0.7879],
        [0.6721, 0.2668, 0.9786, 0.4463],
        [0.7156, 0.2948, 0.5911, 0.6309]])
datatype : torch.float32
shape : torch.Size([3, 4])
device : cpu


In [69]:
# Tensor operations

tensorOp = torch.tensor([1,2,3])
tensorOp + 10

tensor([11, 12, 13])

In [71]:
tensorOp*10

tensor([10, 20, 30])

In [72]:
tensorOp - 10

tensor([-9, -8, -7])

In [73]:
torch.mul(tensorOp,10)

tensor([10, 20, 30])

In [75]:
torch.add(tensorOp,10)

tensor([11, 12, 13])

In [17]:
# Matrix multiplication or Dot product of matrix
# Doing matrix multiplication with code without pytorch

matrixA = [[1,2,3],[4,5,6]]
matrixB = [[7,8],[9,10],[11,12]]

matrixC = [[0]*2]*2

for i in range(2):
    for j in range(2):
        for x in range(3):
            matrixC[i][j]+=matrixA[i][x] * matrixB[x][j]
            print(f"A : {matrixA[i][x]}, B :{matrixB[x][j]}, X : {x}, j : {j}, i : {i}, matrixC[i][j] : {matrixC[i][j]}")

print(matrixC)

A : 1, B :7, X : 0, j : 0, i : 0, matrixC[i][j] : 7
A : 2, B :9, X : 1, j : 0, i : 0, matrixC[i][j] : 25
A : 3, B :11, X : 2, j : 0, i : 0, matrixC[i][j] : 58
A : 1, B :8, X : 0, j : 1, i : 0, matrixC[i][j] : 8
A : 2, B :10, X : 1, j : 1, i : 0, matrixC[i][j] : 28
A : 3, B :12, X : 2, j : 1, i : 0, matrixC[i][j] : 64
A : 4, B :7, X : 0, j : 0, i : 1, matrixC[i][j] : 86
A : 5, B :9, X : 1, j : 0, i : 1, matrixC[i][j] : 131
A : 6, B :11, X : 2, j : 0, i : 1, matrixC[i][j] : 197
A : 4, B :8, X : 0, j : 1, i : 1, matrixC[i][j] : 96
A : 5, B :10, X : 1, j : 1, i : 1, matrixC[i][j] : 146
A : 6, B :12, X : 2, j : 1, i : 1, matrixC[i][j] : 218
[[197, 218], [197, 218]]
