![reference image](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

In [ ]:
import torch
import pandas as pd
import numpy as np

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Get tensor back as Python integer
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
# ndim is number of dimensions
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
matrix = torch.tensor([[5,6],[3,4]])
matrix

tensor([[5, 6],
        [3, 4]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [21]:
# Tensor
tensor = torch.tensor([[[1,2,3],[3,5,6],[3,4,8]],[[3,9,7],[4,7,5],[1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [3, 5, 6],
         [3, 4, 8]],

        [[3, 9, 7],
         [4, 7, 5],
         [1, 2, 3]]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

torch.Size([2, 3, 3])

In [24]:
tensor[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [3, 4, 8]])

In [ ]:
## Random tensors