![reference image](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

In [85]:
import torch
import pandas as pd
import numpy as np

In [86]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [87]:
scalar.ndim

0

In [88]:
#Get tensor back as Python integer
scalar.item()

7

In [89]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [90]:
# ndim is number of dimensions
vector.ndim

1

In [91]:
vector.shape

torch.Size([2])

In [92]:
# Matrix
matrix = torch.tensor([[5,6],[3,4]])
matrix

tensor([[5, 6],
        [3, 4]])

In [93]:
matrix.ndim

2

In [94]:
matrix.shape

torch.Size([2, 2])

In [95]:
# Tensor
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [96]:
tensor.ndim

1

In [97]:
tensor.shape

torch.Size([3])

In [98]:
tensor[0]

tensor(1)

In [99]:
## Random tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6674, 0.9389, 0.3291, 0.5850],
        [0.0422, 0.4563, 0.8886, 0.0729],
        [0.6254, 0.4837, 0.8608, 0.0601]])

In [100]:
# Random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.ndim

3

In [101]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [102]:
# Zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [103]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [104]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [105]:
# Range of tensors
range_tensor = torch.arange(start = 0, end=500, step=45)
range_tensor

tensor([  0,  45,  90, 135, 180, 225, 270, 315, 360, 405, 450, 495])

In [106]:
# Tensors like
# Creates a tensor with the same shape as the input tensor
zeros = torch.zeros_like(input=range_tensor)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [107]:
# Tensor datatypes
tensorFloat32 = torch.tensor([3.0,5.0,4.0],dtype=torch.float32,device=None,requires_grad=False)
print(f"This is tensor : {tensorFloat32}, this is datatype : {tensorFloat32.dtype}")

This is tensor : tensor([3., 5., 4.]), this is datatype : torch.float32


In [108]:
tensorFloat16 = tensorFloat32.type(torch.float16)
tensorFloat16

tensor([3., 5., 4.], dtype=torch.float16)

In [109]:
tensorFloat16*tensorFloat32

tensor([ 9., 25., 16.])

In [110]:
tensorInt32 = torch.tensor([3,4,5],dtype=torch.int32)
tensorInt32

tensor([3, 4, 5], dtype=torch.int32)

In [111]:
tensorInt32*tensorFloat16

tensor([ 9., 20., 20.], dtype=torch.float16)

In [112]:
# Solving issues

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4841, 0.2330, 0.6721, 0.7978],
        [0.8380, 0.3625, 0.6818, 0.3929],
        [0.5926, 0.3087, 0.8004, 0.2434]])

In [113]:
print(some_tensor)
print(f"datatype : {some_tensor.dtype}")
print(f"shape : {some_tensor.shape}")
print(f"device : {some_tensor.device}")

tensor([[0.4841, 0.2330, 0.6721, 0.7978],
        [0.8380, 0.3625, 0.6818, 0.3929],
        [0.5926, 0.3087, 0.8004, 0.2434]])
datatype : torch.float32
shape : torch.Size([3, 4])
device : cpu


In [114]:
# Tensor operations

tensorOp = torch.tensor([1,2,3])
tensorOp + 10

tensor([11, 12, 13])

In [115]:
tensorOp*10

tensor([10, 20, 30])

In [116]:
tensorOp - 10

tensor([-9, -8, -7])

In [117]:
torch.mul(tensorOp,10)

tensor([10, 20, 30])

In [118]:
torch.add(tensorOp,10)

tensor([11, 12, 13])

In [119]:
# Matrix multiplication or Dot product of matrix
print(tensor,"*",tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [120]:
torch.matmul(tensor,tensor)

tensor(14)

In [121]:
tensor @ tensor

tensor(14)

In [122]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.2507, 0.4695, 0.0827],
        [0.0454, 0.1105, 0.0098],
        [0.2685, 0.4449, 0.1003]])

In [123]:
torch.rand(2,3) @ torch.rand(3,2)

tensor([[0.6238, 0.8143],
        [0.5936, 0.7295]])

In [128]:
# Shape error
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,8],[9,10],[11,12]])

torch.mm(tensor_B,tensor_A)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [129]:
# Fixing error
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [130]:
tensor_B = tensor_B.T
torch.mm(tensor_A,tensor_B)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])