![reference image](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

In [2]:
import torch
import pandas as pd
import numpy as np

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python integer
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# ndim is number of dimensions
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[5,6],[3,4]])
matrix

tensor([[5, 6],
        [3, 4]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Tensor
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [13]:
tensor.ndim

1

In [14]:
tensor.shape

torch.Size([3])

In [15]:
tensor[0]

tensor(1)

In [16]:
## Random tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1230, 0.1460, 0.5375, 0.5224],
        [0.0070, 0.1953, 0.7073, 0.4688],
        [0.1468, 0.1926, 0.4708, 0.0540]])

In [17]:
# Random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.ndim

3

In [18]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [19]:
# Zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
# Range of tensors
range_tensor = torch.arange(start = 0, end=500, step=45)
range_tensor

tensor([  0,  45,  90, 135, 180, 225, 270, 315, 360, 405, 450, 495])

In [23]:
# Tensors like
# Creates a tensor with the same shape as the input tensor
zeros = torch.zeros_like(input=range_tensor)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# Tensor datatypes
tensorFloat32 = torch.tensor([3.0,5.0,4.0],dtype=torch.float32,device=None,requires_grad=False)
print(f"This is tensor : {tensorFloat32}, this is datatype : {tensorFloat32.dtype}")

This is tensor : tensor([3., 5., 4.]), this is datatype : torch.float32


In [25]:
tensorFloat16 = tensorFloat32.type(torch.float16)
tensorFloat16

tensor([3., 5., 4.], dtype=torch.float16)

In [26]:
tensorFloat16*tensorFloat32

tensor([ 9., 25., 16.])

In [27]:
tensorInt32 = torch.tensor([3,4,5],dtype=torch.int32)
tensorInt32

tensor([3, 4, 5], dtype=torch.int32)

In [28]:
tensorInt32*tensorFloat16

tensor([ 9., 20., 20.], dtype=torch.float16)

In [29]:
# Solving issues

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4133, 0.9121, 0.0620, 0.8126],
        [0.3458, 0.2527, 0.6880, 0.4301],
        [0.8048, 0.0292, 0.9453, 0.5458]])

In [30]:
print(some_tensor)
print(f"datatype : {some_tensor.dtype}")
print(f"shape : {some_tensor.shape}")
print(f"device : {some_tensor.device}")

tensor([[0.4133, 0.9121, 0.0620, 0.8126],
        [0.3458, 0.2527, 0.6880, 0.4301],
        [0.8048, 0.0292, 0.9453, 0.5458]])
datatype : torch.float32
shape : torch.Size([3, 4])
device : cpu


In [31]:
# Tensor operations

tensorOp = torch.tensor([1,2,3])
tensorOp + 10

tensor([11, 12, 13])

In [32]:
tensorOp*10

tensor([10, 20, 30])

In [33]:
tensorOp - 10

tensor([-9, -8, -7])

In [34]:
torch.mul(tensorOp,10)

tensor([10, 20, 30])

In [35]:
torch.add(tensorOp,10)

tensor([11, 12, 13])

In [36]:
# Matrix multiplication or Dot product of matrix
print(tensor,"*",tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [37]:
torch.matmul(tensor,tensor)

tensor(14)

In [38]:
tensor @ tensor

tensor(14)

In [39]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.1691, 0.2372, 0.1076],
        [0.1517, 0.3075, 0.0943],
        [0.2825, 0.3479, 0.1809]])

In [40]:
torch.rand(2,3) @ torch.rand(3,2)

tensor([[1.6800, 1.9483],
        [1.1790, 1.5294]])

In [41]:
# Shape error
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,8],[9,10],[11,12]])

torch.mm(tensor_B,tensor_A)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [42]:
# Fixing error
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [43]:
tensor_B = tensor_B.T
torch.mm(tensor_A,tensor_B)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [44]:
#min, max, mean, sum
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [45]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [46]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [47]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
# Finding the positional min or max
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [49]:
# Reshaping, stacking, squeezing and unsqueezing tensors

x = torch.arange(1.,10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [50]:
# Reshape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [51]:
# Change the view
z = x.view(1,9)
z, z.shape, z.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [52]:
# View of the tensor share the same memory as the original
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
# Stack tensors
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [54]:
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
x_stacked = torch.hstack((x,x,x,x))
x_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [56]:
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [57]:
# Squeeze

print(f"original tensor : {x_reshaped}")
print(f"squeezed tensor : {x_reshaped.squeeze()}")
x_squeezed = x_reshaped.squeeze()
print(f"original shape : {x_reshaped.shape}")
print(f"squeezed shape : {x_squeezed.shape}")

original tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
squeezed tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
original shape : torch.Size([1, 9])
squeezed shape : torch.Size([9])


In [58]:
# Unsqueeze

print(f"previous : {x_squeezed}")
print(f"previous shape : {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"new tensor : {x_unsqueezed}")
print(f"new shape : {x_unsqueezed.shape}")

previous : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape : torch.Size([9])
new tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape : torch.Size([1, 9])


In [59]:
# permute rearranges the dimensions of a tensor in specified order

x_org = torch.rand(size=(224,224,3))

x_permuted = x_org.permute(2,0,1)

print(f"Original shape : {x_org.shape}")
print(f"Permuted shape : {x_permuted.shape}")

Original shape : torch.Size([224, 224, 3])
Permuted shape : torch.Size([3, 224, 224])


In [60]:
# Indexing

x_ind = torch.arange(1,10).reshape(1,3,3)

x_ind, x_ind.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
x_ind[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
x_ind[0,0]

tensor([1, 2, 3])

In [63]:
x_ind[0,0,0]

tensor(1)

In [64]:
x_ind[0,2,:], x_ind[0,:,2]

(tensor([7, 8, 9]), tensor([3, 6, 9]))

In [65]:
# Numpy array to tensor

array = np.arange(1.,9.)
tensor_np = torch.from_numpy(array)

print(f"array type : {array.dtype}, tensor_np type : {tensor_np.dtype}")

array type : float64, tensor_np type : torch.float64


In [66]:
tensor_np = torch.from_numpy(array).type(torch.float32)
print(f"array type : {array.dtype}, tensor_np type : {tensor_np.dtype}")

array type : float64, tensor_np type : torch.float32


In [67]:
array[0] = 9.

tensor_np[0], array[0]

(tensor(1.), 9.0)

In [68]:
# Tensor to numpy

tensor_x = torch.ones(8)
numpy_tensor = tensor_x.numpy()

In [69]:
tensor_x, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [70]:
tensor_x.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [71]:
# Reproducibility and random seed
rand_tensorA = torch.rand(3,4)
rand_tensorB = torch.rand(3,4)
print(rand_tensorA)
print(rand_tensorB)
print(rand_tensorA == rand_tensorB)

tensor([[0.2561, 0.2845, 0.7407, 0.1587],
        [0.5857, 0.9707, 0.5356, 0.8592],
        [0.7661, 0.5119, 0.2663, 0.6789]])
tensor([[0.5793, 0.9773, 0.0863, 0.9662],
        [0.9831, 0.2348, 0.5232, 0.3352],
        [0.5703, 0.1897, 0.6340, 0.0313]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
# making tensors reproducible but random
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_tensorC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rand_tensorD = torch.rand(3,4)

print(rand_tensorC)
print(rand_tensorD)
print(rand_tensorC == rand_tensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [74]:
# Using cuda
tensor_cuda = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [76]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

# It is still on cpu because I am writing this code on my laptop it will be cuda if I were to run it on Google Colab

(tensor([1, 2, 3]), device(type='cpu'))

In [79]:
# NumPy only works with CPU

# Moving tensors back with CPU

tensor_on_gpu.cpu(), tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))