![reference image](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

In [ ]:
import torch
import pandas as pd
import numpy as np

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Get tensor back as Python integer
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
# ndim is number of dimensions
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
matrix = torch.tensor([[5,6],[3,4]])
matrix

tensor([[5, 6],
        [3, 4]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [21]:
# Tensor
tensor = torch.tensor([[[1,2,3],[3,5,6],[3,4,8]],[[3,9,7],[4,7,5],[1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [3, 5, 6],
         [3, 4, 8]],

        [[3, 9, 7],
         [4, 7, 5],
         [1, 2, 3]]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

torch.Size([2, 3, 3])

In [24]:
tensor[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [3, 4, 8]])

In [25]:
## Random tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3951, 0.1169, 0.0232, 0.2959],
        [0.2254, 0.6417, 0.5325, 0.4821],
        [0.0996, 0.9306, 0.8601, 0.6633]])

In [27]:
# Random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.ndim

3

In [28]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [29]:
# Zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
# Range of tensors
range_tensor = torch.arange(start = 0, end=500, step=45)
range_tensor

tensor([  0,  45,  90, 135, 180, 225, 270, 315, 360, 405, 450, 495])

In [44]:
# Tensors like
# Creates a tensor with the same shape as the input tensor
zeros = torch.zeros_like(input=range_tensor)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
# Tensor datatypes
tensorFloat32 = torch.tensor([3.0,5.0,4.0],dtype=torch.float32,device=None,requires_grad=False)
print(f"This is tensor : {tensorFloat32}, this is datatype : {tensorFloat32.dtype}")

This is tensor : tensor([3., 5., 4.]), this is datatype : torch.float32


In [54]:
tensorFloat16 = tensorFloat32.type(torch.float16)
tensorFloat16

tensor([3., 5., 4.], dtype=torch.float16)

In [55]:
tensorFloat16*tensorFloat32

tensor([ 9., 25., 16.])

In [56]:
tensorInt32 = torch.tensor([3,4,5],dtype=torch.int32)
tensorInt32

tensor([3, 4, 5], dtype=torch.int32)

In [58]:
tensorInt32*tensorFloat16

tensor([ 9., 20., 20.], dtype=torch.float16)

In [59]:
# Solving issues

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8349, 0.3782, 0.5964, 0.7879],
        [0.6721, 0.2668, 0.9786, 0.4463],
        [0.7156, 0.2948, 0.5911, 0.6309]])

In [61]:
print(some_tensor)
print(f"datatype : {some_tensor.dtype}")
print(f"shape : {some_tensor.shape}")
print(f"device : {some_tensor.device}")

tensor([[0.8349, 0.3782, 0.5964, 0.7879],
        [0.6721, 0.2668, 0.9786, 0.4463],
        [0.7156, 0.2948, 0.5911, 0.6309]])
datatype : torch.float32
shape : torch.Size([3, 4])
device : cpu


In [69]:
# Tensor operations

tensorOp = torch.tensor([1,2,3])
tensorOp + 10

tensor([11, 12, 13])

In [71]:
tensorOp*10

tensor([10, 20, 30])

In [72]:
tensorOp - 10

tensor([-9, -8, -7])

In [73]:
torch.mul(tensorOp,10)

tensor([10, 20, 30])

In [75]:
torch.add(tensorOp,10)

tensor([11, 12, 13])

In [46]:
# Matrix multiplication or Dot product of matrix
# Doing matrix multiplication with code without pytorch

matrixA = ([[1,2,3],[4,5,6]])
matrixB = ([[7,8],[9,10],[11,12]])

matrixC = np.zeros([2, 2], dtype=int)

print(matrixC)
for i in range(2):
    for j in range(2):
        for x in range(3):
            matrixC[i][j]+=matrixA[i][x] * matrixB[x][j]

print(matrixC)

[[0 0]
 [0 0]]
[[ 58  64]
 [139 154]]


In [138]:
# Finding position where min or max occur at
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [139]:
index = 0
max = x[0]
for i in range(1,len(x)):
    if(x[i]>max):
        max = x[i]
        index = i

max, index

(tensor(90), 9)

In [140]:
index = 0
min = x[0]
for i in range(1,len(x)):
    if(x[i]<min):
        min = x[i]
        index = i

min, index

(tensor(0), 0)

In [142]:
tensor_temp = torch.tensor([2,5,3,7,8,1])

In [143]:
index = 0
max = tensor_temp[0]
for i in range(1,len(tensor_temp)):
    if(tensor_temp[i]>max):
        max = tensor_temp[i]
        index = i

max, index

(tensor(8), 4)

In [144]:
index = 0
min = tensor_temp[0]
for i in range(1,len(tensor_temp)):
    if(tensor_temp[i]<min):
        min = tensor_temp[i]
        index = i

min, index

(tensor(1), 5)

In [214]:
# Permute

x_org = torch.rand(size = (5,5,2))

x_permute = x_org.permute(2,0,1)

print(f"x_org.shape = {x_org.shape}")
print(f"x_permute.shape = {x_permute.shape}")

x_org.shape = torch.Size([5, 5, 2])
x_permute.shape = torch.Size([2, 5, 5])


In [216]:
x_org

tensor([[[0.1527, 0.6018],
         [0.9657, 0.9045],
         [0.2745, 0.9725],
         [0.2225, 0.8949],
         [0.7725, 0.2470]],

        [[0.4304, 0.0997],
         [0.6504, 0.5511],
         [0.3344, 0.0277],
         [0.0132, 0.3109],
         [0.9377, 0.5301]],

        [[0.7704, 0.9918],
         [0.5780, 0.2027],
         [0.4881, 0.9383],
         [0.5685, 0.3876],
         [0.8233, 0.9050]],

        [[0.2296, 0.1730],
         [0.1997, 0.9033],
         [0.3445, 0.0651],
         [0.6621, 0.8772],
         [0.0442, 0.8453]],

        [[0.9325, 0.2996],
         [0.6882, 0.3173],
         [0.6649, 0.5578],
         [0.9228, 0.8688],
         [0.9772, 0.5964]]])

In [218]:
x_permute

tensor([[[0.1527, 0.9657, 0.2745, 0.2225, 0.7725],
         [0.4304, 0.6504, 0.3344, 0.0132, 0.9377],
         [0.7704, 0.5780, 0.4881, 0.5685, 0.8233],
         [0.2296, 0.1997, 0.3445, 0.6621, 0.0442],
         [0.9325, 0.6882, 0.6649, 0.9228, 0.9772]],

        [[0.6018, 0.9045, 0.9725, 0.8949, 0.2470],
         [0.0997, 0.5511, 0.0277, 0.3109, 0.5301],
         [0.9918, 0.2027, 0.9383, 0.3876, 0.9050],
         [0.1730, 0.9033, 0.0651, 0.8772, 0.8453],
         [0.2996, 0.3173, 0.5578, 0.8688, 0.5964]]])

In [231]:
x_permute[0,:,1] = 5.
x_permute[0,:,1]

tensor([5., 5., 5., 5., 5.])

In [233]:
x_org


## Permute understood

tensor([[[0.1527, 0.6018],
         [5.0000, 0.9045],
         [0.2745, 0.9725],
         [0.2225, 0.8949],
         [0.7725, 0.2470]],

        [[0.4304, 0.0997],
         [5.0000, 0.5511],
         [0.3344, 0.0277],
         [0.0132, 0.3109],
         [0.9377, 0.5301]],

        [[0.7704, 0.9918],
         [5.0000, 0.2027],
         [0.4881, 0.9383],
         [0.5685, 0.3876],
         [0.8233, 0.9050]],

        [[0.2296, 0.1730],
         [5.0000, 0.9033],
         [0.3445, 0.0651],
         [0.6621, 0.8772],
         [0.0442, 0.8453]],

        [[0.9325, 0.2996],
         [5.0000, 0.3173],
         [0.6649, 0.5578],
         [0.9228, 0.8688],
         [0.9772, 0.5964]]])