![reference image](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

In [ ]:
import torch
import pandas as pd
import numpy as np

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Get tensor back as Python integer
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
# ndim is number of dimensions
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
matrix = torch.tensor([[5,6],[3,4]])
matrix

tensor([[5, 6],
        [3, 4]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [21]:
# Tensor
tensor = torch.tensor([[[1,2,3],[3,5,6],[3,4,8]],[[3,9,7],[4,7,5],[1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [3, 5, 6],
         [3, 4, 8]],

        [[3, 9, 7],
         [4, 7, 5],
         [1, 2, 3]]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

torch.Size([2, 3, 3])

In [24]:
tensor[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [3, 4, 8]])

In [25]:
## Random tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3951, 0.1169, 0.0232, 0.2959],
        [0.2254, 0.6417, 0.5325, 0.4821],
        [0.0996, 0.9306, 0.8601, 0.6633]])

In [27]:
# Random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.ndim

3

In [28]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [29]:
# Zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
# Range of tensors
range_tensor = torch.arange(start = 0, end=500, step=45)
range_tensor

tensor([  0,  45,  90, 135, 180, 225, 270, 315, 360, 405, 450, 495])

In [44]:
# Tensors like
# Creates a tensor with the same shape as the input tensor
zeros = torch.zeros_like(input=range_tensor)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])